# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SunRare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'ProgressHUD', '~> 13.6'

end

target 'SunRareExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SunRareExample

end
